# Author:  Niels A.D.
# Project: goop (https://github.com/nielsAD/goop)
# License: Mozilla Public License, v2.0

language: go
go: 1.10.x

os:
  - linux
  - osx

notifications:
  email:
    on_success: false
    on_failure: change

install:
  # Install OS dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update            ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install md5sha1sum; fi

  # Install test dependencies
  - go get github.com/golang/lint/golint

script:
  - make test
  - make release
  - md5sum ./bin/*

before_deploy:
  - tar -czf release_$TRAVIS_OS_NAME.tar.gz bin LICENSE

deploy:
  provider: releases
  api_key:
    secure: hp9fGXwkbzYkWc32yG6eci++j4xUh6prDYItl2nLB/zsCD6r39NtfvoJza8GijJfyY8UNGmg/oWhUicghL11YRtM+VMWVSotumUPYIPFCSd9yRh+W7NKl/hwWzd9OcGzqZS3GR8GXxu9d8S2xLjeTu2iEX/hG+14X2puMlvvXHlGBvDT+7AHPfQZs2doSVmbR9dzscDRFwAZ3ENidD4xIaVJgw2XdE/mD1LlEsD7A9uIYfFTTD2KquG85vt+uJ7g066tutLJ8pp4idydS+Aa1u50OZG4IDY5QI7X6nMJZWI1AA6/csWmWvn/eYl6deDefwAOZ1ceeFj82pZsc9AlX7ulhZyiBVGcojDeumkt+pnryhapqVjW+k3iq9n65Z2boDDx4ImQhsyFERGC4u/VsGr4HEcnkuMF3XImW5Ntx53Grqe5/ReMjMNtJWBrLFFW4v8Gw5LcPTWXn75z7LN0hmmKe9zXOXop8rGTWyfcHRuRPSuAoufwcd8Uvt79QgX9u6J8unthyoGDnfVn3sevXztorZCs5g0o+TfUxnv/nWz1k6KC1vSY2LUZPQKvlBRDsb5aEcGjQBculDr8fqLVfF25BVPwrHwJtsn6NQbzhnxvEkxFRNELftNXHWeVJ+93o/reWS5kPWYC3SDOX0xsmOWtO9BLHMrA5nvWuuTUeeQ=
  file_glob: true
  file: release_*
  skip_cleanup: true
  on:
    tags: true
